// Coldest / warmest avg-day per location and hemisphere.
// `cold` and `hot` are [month, day] (1-indexed). `h` is 'N' or 'S'.
export const locations = [
  { name: "Waterloo, ON", cold: [1, 29], hot: [7, 21], h: "N" },
  { name: "Toronto, ON", cold: [1, 28], hot: [7, 20], h: "N" },
  { name: "Ottawa, ON", cold: [1, 15], hot: [7, 18], h: "N" },
  { name: "Montreal, QC", cold: [1, 14], hot: [7, 18], h: "N" },
  { name: "Vancouver, BC", cold: [12, 28], hot: [8, 2], h: "N" },
  { name: "Calgary, AB", cold: [1, 10], hot: [7, 17], h: "N" },
  { name: "Edmonton, AB", cold: [1, 8], hot: [7, 15], h: "N" },
  { name: "Winnipeg, MB", cold: [1, 10], hot: [7, 19], h: "N" },
  { name: "Halifax, NS", cold: [2, 2], hot: [7, 28], h: "N" },
  { name: "Sudbury, ON", cold: [1, 18], hot: [7, 18], h: "N" },
  { name: "New York, NY", cold: [1, 29], hot: [7, 22], h: "N" },
  { name: "Chicago, IL", cold: [1, 21], hot: [7, 20], h: "N" },
  { name: "Boston, MA", cold: [1, 25], hot: [7, 22], h: "N" },
  { name: "Minneapolis, MN", cold: [1, 13], hot: [7, 19], h: "N" },
  { name: "Denver, CO", cold: [12, 25], hot: [7, 14], h: "N" },
  { name: "Detroit, MI", cold: [1, 27], hot: [7, 20], h: "N" },
  { name: "Philadelphia, PA", cold: [1, 28], hot: [7, 22], h: "N" },
  { name: "Seattle, WA", cold: [12, 28], hot: [8, 3], h: "N" },
  { name: "Portland, OR", cold: [12, 26], hot: [8, 1], h: "N" },
  { name: "San Francisco, CA", cold: [1, 1], hot: [9, 15], h: "N" },
  { name: "Los Angeles, CA", cold: [12, 22], hot: [8, 15], h: "N" },
  { name: "Miami, FL", cold: [1, 15], hot: [7, 25], h: "N" },
  { name: "Washington, DC", cold: [1, 27], hot: [7, 21], h: "N" },
  { name: "London, UK", cold: [2, 8], hot: [7, 25], h: "N" },
  { name: "Paris, France", cold: [1, 17], hot: [7, 23], h: "N" },
  { name: "Berlin, Germany", cold: [1, 18], hot: [7, 22], h: "N" },
  { name: "Stockholm, Sweden", cold: [2, 2], hot: [7, 22], h: "N" },
  { name: "Helsinki, Finland", cold: [2, 5], hot: [7, 20], h: "N" },
  { name: "Moscow, Russia", cold: [1, 22], hot: [7, 20], h: "N" },
  { name: "Amsterdam, NL", cold: [2, 3], hot: [7, 25], h: "N" },
  { name: "Zurich, Switzerland", cold: [1, 12], hot: [7, 20], h: "N" },
  { name: "Tokyo, Japan", cold: [1, 25], hot: [8, 5], h: "N" },
  { name: "Seoul, S. Korea", cold: [1, 15], hot: [8, 1], h: "N" },
  { name: "Beijing, China", cold: [1, 14], hot: [7, 18], h: "N" },
  { name: "Sydney, Australia", cold: [7, 17], hot: [1, 22], h: "S" },
  { name: "Melbourne, Australia", cold: [7, 20], hot: [1, 28], h: "S" },
  { name: "Auckland, NZ", cold: [7, 22], hot: [2, 2], h: "S" },
  { name: "Buenos Aires, Argentina", cold: [7, 15], hot: [1, 18], h: "S" },
  { name: "São Paulo, Brazil", cold: [7, 18], hot: [2, 5], h: "S" },
  { name: "Cape Town, S. Africa", cold: [7, 20], hot: [2, 8], h: "S" },
];
